# Generated by Django 5.2.2 on 2025-06-16 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_created_at_categoria_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
