# Generated by Django 5.2.2 on 2025-06-17 05:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
