# Generated by Django 5.2.2 on 2025-07-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_remove_categoria_created_by_and_more'),
        ('financial', '0004_remove_contapagarreceber_cliente_and_more'),
        ('inventory', '0004_product_inventorycount_stockmovement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'is_active'], name='core_addres_tenant__9b33f5_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'city'], name='core_addres_tenant__15683a_idx'),
        ),
    ]
