# Generated by Django 5.2.2 on 2025-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encargos_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de encargos sobre o salário base, ex: 25.00 para 25%', max_digits=5, null=True)),
                ('data_proximo_pagamento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
