# Generated by Django 5.2.2 on 2025-06-10 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_produto', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=0)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'Estoque'}, on_delete=django.db.models.deletion.PROTECT, related_name='itens_estoque', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['nome_produto'],
            },
        ),
    ]
