# Generated by Django 5.2.2 on 2025-07-08 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_logo_user_aceite_user_data_cadastro'),
        ('inventory', '0002_rename_created_at_itemestoque_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
