# Generated by Django 5.2.2 on 2025-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mes_ano', models.DateField(help_text='Primeiro dia do mês/ano da meta')),
                ('meta_receita', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('receita_real', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado/atualizado periodicamente ou via trigger', max_digits=12)),
                ('meta_lucro', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lucro_real', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado/atualizado periodicamente ou via trigger', max_digits=12)),
            ],
            options={
                'verbose_name': 'Meta e Resultado',
                'verbose_name_plural': 'Metas e Resultados',
                'ordering': ['-mes_ano'],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('entradas_previstas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saidas_previstas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Projeção de Caixa',
                'verbose_name_plural': 'Projeções de Caixa',
                'ordering': ['data'],
            },
        ),
    ]
