# Generated by Django 5.2.2 on 2025-07-09 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_remove_categoria_created_by_and_more'),
        ('reports', '0003_metaresultado_tenant_projecaocaixa_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecaocaixa',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projecaocaixa',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='projecaocaixa',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.DeleteModel(
            name='MetaResultado',
        ),
        migrations.DeleteModel(
            name='ProjecaoCaixa',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'is_active'], name='reports_rep_tenant__b05d70_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'report_type'], name='reports_rep_tenant__141b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'generated_at'], name='reports_rep_tenant__063965_idx'),
        ),
    ]
